export const blogPosts = [
  {
    title: "My First Post",
    slug: "first",
    date: new Date().toString(),
    content:
      "111111 Throw down all the stuff in the kitchen stare at guinea pigs unwrap toilet paper toilet paper attack claws fluff everywhere meow miao french ciao litterbox meow meow we are 3 small kittens sleeping most of our time, we are around 15 weeks old i think, i don’t know i can’t count. Sees bird in air, breaks into cage and attacks creature damn that dog steal mom's crouton while she is in the bathroom, dead stare with ears cocked. The fat cat sat on the mat bat away with paws. Snob you for another person crash against wall but walk away like nothing happened for kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff for pushed the mug off the table purrr purr littel cat, little cat purr purr or bite off human's toes. I love cuddles hiss and stare at nothing then run suddenly away in the middle of the night i crawl onto your chest and purr gently to help you sleep stare at ceiling light for cat snacks you call this cat food eat owner's food. Sees bird in air, breaks into cage and attacks creature lick human with sandpaper tongue, yet sit and stare so cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit leave buried treasure in the sandbox for the toddlers. Lick butt and make a weird face climb into cupboard and lick the salt off rice cakes knock over christmas tree shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff yet sleep everywhere, but not in my bed but leave hair on owner's clothes. Jump five feet high and sideways when a shadow moves man running from cops stops to pet cats, goes to jail but slap kitten brother with paw yet cat cat moo moo lick ears lick paws but fall over dead (not really but gets sypathy). Paw at beetle and eat it before it gets away. Meow go back to sleep owner brings food and water tries to pet on head, so scratch get sprayed by water because bad cat snob you for another person. Cat cat moo moo lick ears lick paws. Gate keepers of hell eat fish on floor meeeeouw lie in the sink all day so destroy house in 5 seconds. Making sure that fluff gets into the owner's eyes cats making all the muffins for meow meow mama. Hack mrow and eat a plant, kill a hand. Be superior man running from cops stops to pet cats, goes to jail sleeps on my head chase mice, yet i vomit in the bed in the middle of the night leave dead animals as gifts, and meow to be let out.",
  },
  {
    title: "My 2nd Post",
    slug: "second",
    date: new Date().toString(),
    content:
      "22222222222 Throw down all the stuff in the kitchen stare at guinea pigs unwrap toilet paper toilet paper attack claws fluff everywhere meow miao french ciao litterbox meow meow we are 3 small kittens sleeping most of our time, we are around 15 weeks old i think, i don’t know i can’t count. Sees bird in air, breaks into cage and attacks creature damn that dog steal mom's crouton while she is in the bathroom, dead stare with ears cocked. The fat cat sat on the mat bat away with paws. Snob you for another person crash against wall but walk away like nothing happened for kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff for pushed the mug off the table purrr purr littel cat, little cat purr purr or bite off human's toes. I love cuddles hiss and stare at nothing then run suddenly away in the middle of the night i crawl onto your chest and purr gently to help you sleep stare at ceiling light for cat snacks you call this cat food eat owner's food. Sees bird in air, breaks into cage and attacks creature lick human with sandpaper tongue, yet sit and stare so cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit leave buried treasure in the sandbox for the toddlers. Lick butt and make a weird face climb into cupboard and lick the salt off rice cakes knock over christmas tree shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff yet sleep everywhere, but not in my bed but leave hair on owner's clothes. Jump five feet high and sideways when a shadow moves man running from cops stops to pet cats, goes to jail but slap kitten brother with paw yet cat cat moo moo lick ears lick paws but fall over dead (not really but gets sypathy). Paw at beetle and eat it before it gets away. Meow go back to sleep owner brings food and water tries to pet on head, so scratch get sprayed by water because bad cat snob you for another person. Cat cat moo moo lick ears lick paws. Gate keepers of hell eat fish on floor meeeeouw lie in the sink all day so destroy house in 5 seconds. Making sure that fluff gets into the owner's eyes cats making all the muffins for meow meow mama. Hack mrow and eat a plant, kill a hand. Be superior man running from cops stops to pet cats, goes to jail sleeps on my head chase mice, yet i vomit in the bed in the middle of the night leave dead animals as gifts, and meow to be let out.",
  },
  {
    title: "My 3rd Post",
    slug: "third",
    date: new Date().toString(),
    content:
      "3333333 Throw down all the stuff in the kitchen stare at guinea pigs unwrap toilet paper toilet paper attack claws fluff everywhere meow miao french ciao litterbox meow meow we are 3 small kittens sleeping most of our time, we are around 15 weeks old i think, i don’t know i can’t count. Sees bird in air, breaks into cage and attacks creature damn that dog steal mom's crouton while she is in the bathroom, dead stare with ears cocked. The fat cat sat on the mat bat away with paws. Snob you for another person crash against wall but walk away like nothing happened for kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff for pushed the mug off the table purrr purr littel cat, little cat purr purr or bite off human's toes. I love cuddles hiss and stare at nothing then run suddenly away in the middle of the night i crawl onto your chest and purr gently to help you sleep stare at ceiling light for cat snacks you call this cat food eat owner's food. Sees bird in air, breaks into cage and attacks creature lick human with sandpaper tongue, yet sit and stare so cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit leave buried treasure in the sandbox for the toddlers. Lick butt and make a weird face climb into cupboard and lick the salt off rice cakes knock over christmas tree shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff yet sleep everywhere, but not in my bed but leave hair on owner's clothes. Jump five feet high and sideways when a shadow moves man running from cops stops to pet cats, goes to jail but slap kitten brother with paw yet cat cat moo moo lick ears lick paws but fall over dead (not really but gets sypathy). Paw at beetle and eat it before it gets away. Meow go back to sleep owner brings food and water tries to pet on head, so scratch get sprayed by water because bad cat snob you for another person. Cat cat moo moo lick ears lick paws. Gate keepers of hell eat fish on floor meeeeouw lie in the sink all day so destroy house in 5 seconds. Making sure that fluff gets into the owner's eyes cats making all the muffins for meow meow mama. Hack mrow and eat a plant, kill a hand. Be superior man running from cops stops to pet cats, goes to jail sleeps on my head chase mice, yet i vomit in the bed in the middle of the night leave dead animals as gifts, and meow to be let out.",
  },
];
